config/routes.rb
Rails.application.routes.draw do
  # /collages/:collage_id
  resources :collages do
    resources :designs, only: [:index, :new, :create]
  end
  
  resources :designs 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/designs', to: 'designs#index' # index - list all designs
  # get '/designs/new', to: 'designs#new' # new - new form
  # post '/designs', to: 'designs#create' # create - post from the new form
  
  # get '/designs/:id/edit', to: 'designs#edit' #edit - 
  # patch '/designs/:id', to: 'designs#update' #update
  # put '/designs/:id', to: 'designs#update' #update

  # delete '/designs/:id', to: 'designs#destroy' #destroy
 
  # get '/designs/:id', to: 'designs#show', as: 'design' # show
  #custom route                     
  get '/most_recent', to: 'designs#most_recent', as: 'recent'
  get '/search', to: 'designs#search', as: 'search'
  # as: 'recent' => recent_path
  # recent_path = '/most_recent'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collage.rb
class Collage < ApplicationRecord
    has_many :images
    validates :name, presence: true
    accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes['title'].blank? || attributes['description'].blank? || attributes['image_url'].blank? }
end

app/models/design.rb
class Design < ApplicationRecord
    validates :title, presence: true, uniqueness: {scope: :design_url, message: 'and design Url are not UNIQUE'}
    validates :description, presence: true
    validates :design_url, presence: true
    belongs_to :collage, optional: true # collage= COLLAGE OBJECT

    # accepts_nested_attributes_for :collage
    # collage_attributes=(attributes) 

    def uploaded_at
        self.created_at.to_date
    end

    def collage_attributes=(attributes)

        if !(attributes[:name].blank? || attributes[:description].blank?)
            self.collage = Collage.find_or_create_by(attributes)
        end
    end


    # validates :views, numericality: { less_than: 10 }
    # validate :too_many_designs, on: :create
    
    # custom validation called design url format
    # add validator that checks if the design_url ends with
    # .jpg
    # .jpeg
    # .png

    # def too_many_designs
    #     if design.all.length >= 10
    #         self.errors.add(:base, :invalid, message: "MY DATABASE IS FULL STOP CREATING designS")
    #     end
    # end
    
    
    # TODO: Refactor to scope method
    def self.search(query)
        self.where("title LIKE ?", "%#{query}%")
    end

    def self.most_recent
        self.order(created_at: :desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user   

    private 

    def current_user
        @user = User.find_by(id: sessions[:user_id]) 
    end

end

app/controllers/collages_controller.rb
class CollagesController < ApplicationController
    layout 'studio', only: [:new, :edit, :create, :update]

    def new
        @collage = Collage.new
        # @collage.designs << design.new
        3.times{ @collage.designs.build } 
    end

    def edit
        @collage = Collage.find(params[:id])
    end

    def create
        @collage = Collage.new(collage_params)

        if @collage.save
            redirect_to collage_path(@collage)
        else
            render :new
        end
    end

    def index
        @collages = Collage.all
    end

    def show
        @collage = Collage.find(params[:id])

    end

    private

    def collage_params
        params.require(:collage).permit(:name, :description, designs_attributes: [:title, :description, :design_url])
    end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
    before_action :find_collage, only: [:index, :new, :create]

    def search
        @designs = Design.search(params[:title])
        render :index
    end

    def most_recent
        @designs = Design.most_recent
    end

    def index
        if @collage
            @designs = @collage.designs
        else
            @designs = Design.all
        end
    end
    
    def show
        @design = Design.find_by(id: params[:id])
        @design.update(views: @design.views+1) 
    end
    
    def new
        if @collage
            @design = @collage.designs.build
        else
            @design = Design.new
            @design.build_collage
        end

        render layout: 'studio'
    end

    def create
        # if @collage
        #     @design = @collage.designs.build(design_params)
        # else
        #     @design = design.new(design_params)
            
        # end
        @design = Design.new(design_params)
        # What is happening on line 26?
        # creating new design based on params I set.
        # self.send("#{k}=", value)
        if @design.save
            if @collage
                redirect_to collage_designs_path(@collage)
            else
                redirect_to design_path(@design)
            end
        else
            # implement some error handling
            # If it doesnt save
            # @design.errors
            # TODO: add some flash messaging
            
            render :new, layout: "studio"
        end
    end

    def edit
        @design = design.find_by(id: params[:id] )
        render layout: 'studio'
    end

    def update
        @design = Design.find_by(id: params[:id])
        @design.update(design_params)

        if @design.valid?
            redirect_to design_path(@design)
        else
            #TODO: ERROR MESSAGES
            render :edit, layout: 'studio'
        end
    end

    def destroy
        #TODO: DRY THIS UP BRO
        @design = design.find_by(id: params[:id])
        @design.destroy
        redirect_to designs_path
    end

    private
    #Strong Params
    def design_params
        params.require(:design).permit(:title, :description, :design_url, :collage_id, collage_attributes: [:name, :description])
    end

    def find_collage
        @collage = Collage.find_by_id(params[:collage_id])
        #@collage = Collage.find(params[:collage_id]) # will error if id does not exist
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collages_helper.rb
module CollagesHelper
end

app/helpers/designs_helper.rb
module DesignsHelper



    def design_image(design)

        "<%= image_tag(design.design_url) %>"

end
end

app/helpers/designs_helpers.rb
module DesignsHelper
    def fields_for_helper(f)
        if @collage
            f.hidden_field :collage_id, value: @collage.id 
        else 
            render partial: "fields_for", locals: {f: f}  
        end 

    end
    
    def index_header
        if @collage 
            content_tag(:h1, "#{@collage.name} designs")
        else 
            content_tag(:h1, "All Design")
        end 
    end



    def index_date_format(design)
        created = design.created_at.to_datetime
        now = DateTime.now
        seconds = ((now - created) * 24 * 60 * 60).to_i
        minutes = seconds/60
        hours = minutes/60
        days = hours/24
        months = days/30
        years = months/12


        if seconds < 60
            return "#{seconds} seconds ago."
        elsif minutes < 60
            return "#{minutes} minutes ago."    
        elsif hours < 24
            return "#{hours} hours ago."
        elsif days < 30
            return "#{days} days ago."
        elsif months < 12
            return "#{months} months ago."
        else
            return "#{years} years ago."
        end

        
    end
end

app/views/collages/_collage.html.erb
<li><%= link_to(collage.name, collage_path(collage)) %></li>

app/views/collages/_form.html.erb
<%= form_with(model: model) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <h3> <%= form_title %></h3>
    <%= f.fields_for :designs do |i| %>
      <%= i.label :title %>
      <%= i.text_field :title %><br>
      <%= i.label :description %>
      <%= i.text_field :description %><br>
      <%= i.label :design_url %>
      <%= i.text_field :design_url %><br>
      <hr>
    <% end %>
  
    
    <%= f.submit button_name %>
<% end %>

app/views/collages/edit.html.erb
  
<h1> EDIT COLLAGE </h1>
<%= render partial: 'errors/errors', locals: {model: @collage } %>
<%= render partial: 'form', locals: { form_title: "EDIT DESIGNS", model: @collage, button_name: "EDIT Collage"  } %>

app/views/collages/index.html.erb
<h1> All Collages </h1>

<ul>
    <%= render @collages %>
</ul>

app/views/collages/new.html.erb
<h1> Create New Collage </h1>
<%= render partial: 'errors/errors', locals: {model: @collage } %>
<%= render partial: 'form', locals: { form_title: "CREATE A NEW DESIGN", model: @collage, button_name: "Create Collage"  } %>

app/views/collages/show.html.erb
<h1><%= @collage.name %></h1>
<div>
    <p> <%= @collage.description %></p>
</div>

<h1>THIS COLLAGES DESIGNS: </h1>
<%= link_to "Takes us to collage Designs path", collage_designs_path(@collage) %>
<ul>
<% @collage.designs.each do |img| %>
    <li><%= link_to(img.title, design_path(img)) %> - <%= index_date_format(img) %></li>
<% end %>
</ul>

<%= link_to 'back', collages_path %>

app/views/designs/_fields_for.html.erb
<h3> SELECT A EXISTING COLLAGE </h3>
<%#= collection_select(:post, :author_id, Author.all, :id, :name_with_initial, prompt: true) %>
<%= f.collection_select(:collage_id, Collage.all, :id, :name) %>

<h3> CREATE A NEW COLLAGE</h3>
<%#= name, description %>
<%= f.fields_for :collage do |c| %>
    <%= c.label :name %>
    <%= c.text_field :name %><br>
    <%= c.label :description %>
    <%= c.text_field :description %><br>
<% end %>

app/views/designs/_image.html.erb
<li><%= link_to(design.title, image_path(design)) %> - <%= index_date_format(design) %></li>

app/views/designs/edit.html.erb
<h1> EDIT A DESIGN </h1>

<%= render partial: 'errors/errors', locals: {model: @design} %>
<%= form_with(model: @design) do |f| %>
   <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <%= f.label :design_url %>
    <%= f.text_field :design_url %><br>
    <%= f.submit 'Update design' %>
<% end %>
<%= link_to "DELETE design", design_path(@design), method: "delete" %>

app/views/designs/index.html.erb
<h1> All Designs </h1>

<ul>
<% @designs.each do |img| %>
    <li><%= link_to(img.title, design_path(img)) %> - <%= img.uploaded_at %></li>
<% end %>
</ul>

app/views/designs/most_recent.html.erb
<h1> Most Recent </h1>
<ul>

<% @designs.each do |des| %>

<li><%= link_to(des.title, design_path(des)) %> <%= des.uploaded_at %></li>

<% end %>
</ul>

app/views/designs/new.html.erb
  
<h1> Create New Design </h1>

<%= render partial: 'errors/errors', locals: {model: @design} %>
<%= form_with(model: [@collage, @design]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <%= f.label :design_url %>
    <%= f.text_field :design_url %><br>
    <%= fields_for_helper(f) %>
    <%= f.submit 'Create design' %>
<% end %>

app/views/designs/show.html.erb
<%= render partial: 'errors/errors', locals: {model: @design} %>
<%= design_tag(@design.design_url) %>
<h1><%= @design.title %></h1>
<div>
    <p> <%= format_created_at(@design) %></p>
    <p> <%= @design.description %></p>
    <p> Views: <%= @design.views %></p>
    <p> Likes: <%= @design.likes %></p>
    <p> Dislikes: <%= @design.dislikes %></p>
</div>

<%= link_to 'back', designs_path %>
<%= link_to 'Edit', edit_design_path(@design) %>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-light bg-light">
    <div class="d-flex">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= design_tag('logo.png', width: '60px', height: '30px') %>
        <%= logo_name %>
      </a>
        <%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
          <%= f.text_field :title, class: "form-control me-2", placeholder: "Search for Title" %>
          <%= f.submit :Search, class: "btn btn-outline-success" %>
        <% end %>
      
  </nav>

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/designs">Home</a>
        </li>
        <li>
            <%= link_to 'Create New design', new_design_path, class: 'nav-link active' %>
        </li>
        <li>
            <%= link_to 'Most Recent PATH', recent_path, class: 'nav-link active' %>
        </li>
        <li>
            <%= link_to 'All Collages', collages_path, class: 'nav-link active' %>
        </li>
        <li>
            <%= link_to 'New Collage Path', new_collage_path, class: 'nav-link active' %>
        </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Designtube</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">DesignTube</a>
    <%# here the name is changed to DesignTube because of the changes in the above line %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/designs">Home</a> 
          <%# this takes us to designs once we click on home in the above line %>
        </li>

<li> <%# this is how we use link_to %>
<%= link_to "Most Recent", recent_path, class: 'nav-link active' %>
</li>

<li>
<%= link_to "Create new Design", new_design_path, class: 'nav-link active' %>
</li>

      </ul>

      <%# this lower part starting from form is for search %>
      <form class="d-flex" action="/designs" method="GET">
        <input class="form-control me-2" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    <%= yield %>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/studio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial: "layouts/nav", locals: { logo_name: "Studio"}) %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          <%= render partial: "layouts/sidebar" %>
        </div>
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>